### ISSUE TITLE
Add Node 20 (and maybe 22) to the CI

### ISSUE THREAD

**Issue by qbzzt** [latticexyz/mud#2466]
We need this to happen before we can allow people to use them.

**Comment by roaminro** [comment]
@qbzzt @holic Do you want to add these node versions to all the ci workflows or only some of them?
To run additional versions of node you basically need to use matrices which means that a job is created per node version. So if you were to run node 18, 20 and 22 for the "test" workflow, you'd have 3 jobs running for that one workflow and since you have many workflows I wonder if that's really necessary? (it would probably triple your CI costs)

Another thing to keep in mind, matrices don't directly work with "composite" actions, which means you can't directly use them in the `.github/actions/setup-prerequisites/action.yml` composite action for example. To use matrices you'd need to modify the "main" workflow, an example with the "test" workflow.

the file `.github/actions/setup-prerequisites/action.yml` would need to be modified like this:

```
jobs:
  test:
    name: Run tests (Node.js v${{ matrix.node }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [ 18, 20, 22 ]
    services:
      ...
    steps:
      ...

      - name: Setup
        if: steps.check_changes.outputs.changes_outside_docs
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}

      ...
```

then you'd have to pass the "node-version" param all the way down to the composite action `.github/actions/setup-prerequisites` like so:

```
name: Setup prerequisites
description: Setup pnpm, Node.js, and Foundry
inputs:
 node-version:
    description: 'Node.js version to install'
    required: true
    default: 18
runs:
  using: composite
  steps:
    ...

    - name: Setup node v${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org
        cache: pnpm
    ...
```

I've setup the `test` workflow that way on my MUD fork so you can see what that would look like, see this run https://github.com/roaminro/mud/actions/runs/10017250112 

Let me know if yuo'd like to go with that solution and if so, let me know which workflows should implement it ;)
