### ISSUE TITLE
Possible evm configuration mismatch impacting add table guide

### ISSUE THREAD

**Issue by robinbryce** [latticexyz/mud#3513]
When following the steps outlined at https://mud.dev/guides/hello-world/add-table

In the contracts pane after running `pnpm dev` the error "EvmError: NotActivated" is reported by the PostDeploy.s.sol script

forge --version
forge 0.2.0 (56639cd 2024-11-02T00:20:53.449400000Z)
anvil --version
anvil 0.2.0 (56639cd 2024-11-02T00:20:53.274013000Z)

The exact steps performed

```
pnpm create mud@latest --name tutorial --template vanilla
cd tutorial
pnpm install
pnpm dev
```

(This obtained mud 2.2.16)

```
running "forge script PostDeploy --broadcast --sig run(address) 0xfdf868ea710ffd8cd33b829c5aff79edd15ecd5f --rpc-url http://127.0.0.1:8545 -vvv "
[⠊] Compiling...
No files changed, compilation skipped
Traces:
  [297157] → new PostDeploy@0x9f7cF1d1F558E57ef88a59ac3D47214eF25B6A06
    └─ ← [Return] 1263 bytes of code

  [1056943991] PostDeploy::run(0xfDf868Ea710FfD8cd33b829c5AFf79eDd15EcD5f)
    ├─ [0] VM::envUint("PRIVATE_KEY") [staticcall]
    │   └─ ← [Return] <env var value>
    ├─ [0] VM::startBroadcast(<pk>)
    │   └─ ← [Return] 
    ├─ [39] 0xfDf868Ea710FfD8cd33b829c5AFf79eDd15EcD5f::app__increment()
    │   └─ ← [NotActivated] EvmError: NotActivated
    └─ ← [Revert] EvmError: Revert
```

The world address was reported as

```
 mud:cli:deploy deploying world +0ms
  mud:common:writeContract calling deployWorld at 0x8dC4168Dc8E582F0ef5aDbAB3C0873856682639B with nonce 6 +0ms
  mud:cli:deploy waiting for world deploy +62ms
  mud:cli:deploy deployed world to 0xfdf868ea710ffd8cd33b829c5aff79edd15ecd5f at block 8n +4s
  mud:common:deploy deploying app__IncrementSystem system at 0x2F1C17077D45362ECD27a3d9Ba399791c4Ae7C67 +4s
  mud:common:sendTransaction sending tx to 0x4e59b44847b379578588920ca78fbf26c0b4956c with nonce 7 +4s
```

I found the symbol NotActivated in the foundry-rs sources, and also noticed this issue re inconsistent use of evm_version which may be related - https://github.com/foundry-rs/foundry/issues/6228

I attempted to force the evm version by changing mproc.yaml to

```
procs:
  client:
    cwd: packages/client
    shell: pnpm run dev
  contracts:
    cwd: packages/contracts
    shell: pnpm mud dev-contracts --rpc http://127.0.0.1:8545 --forgeScriptOptions '\"--evm-version paris\"'
  anvil:
    cwd: packages/contracts
    shell: anvil --base-fee 0 --block-time 2 --hardfork paris
  explorer:
    cwd: packages/contracts
    shell: pnpm explorer
```

And also setting evm_version in packages/contracts/foundry.toml

But this caused the contract deployment itself to revert.

I also checked I did not have a global foundry.toml

I can totally believe this is weird config on my end, but confirmation that it cant be reproduced would be great!
